### ISSUE TITLE
CW textbox always open & bonus points for simple yes/no dialog optional

### ISSUE THREAD

**Issue by hoodieak** [unascribed/sleeping.town#43]
it's pretty simple/near the title!

essentially just a setting where the cw toggle dissappears and it remains always open as a textbox.

optional bonus points: textbox in dialog that can be chosen separately from CW always open, that pops up a 'are you sure you want to post without a content warning?', and following that, maybe even a textbox auto-selected to put the CW into a textbox in the dialog for style points

**Comment by unascribed** [comment]
I'm having a bit of trouble parsing the second part of this request

my interpretation is that you want it to, optionally, pop up a dialog if you attempt to post with no/a blank CW, confirming that action, and having a textbox *in the dialog* to fill in the CW, instead of having to cancel the dialog, re-enter, and then click toot again?

**Comment by hoodieak** [comment]
yes!

**Comment by hoodieak** [comment]
https://github.com/glitch-soc/mastodon/commit/171e54eb469ac48830eba2349b3298c004ec19f5 this exists now in glitchsoc
